language: node_js
node_js:
- '4.1'
- '0.11'
- iojs
before_script:
- ./node_modules/.bin/jspm i
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  global:
  - secure: k9ABvCTnQju5QpW1JFTASdDovIhaKcfxdx4SZYfd5n3Cs/n39+cn6RCEVrAeMSgWndGVvdCy+/zFv56T5IQAnSfTTvJUOgY5xBi9EmoUy1owRtAlXSb4+m4tw+6ctY2U5fpBp8ftib04kioxvxVUfTDuKUbbkNIQvAOVjX0CKX/kzNJahaICU8nmihCetgW+G5SCliu2WKU1+vPk2FxctRVxbhzdnsY5wdPUTBxVKgCsiy61szbF1P62Aif1LD3oDARKQWVlh8LRK5FnRzVlqYwM55v1BgI8Fa4W88Ng/rN93cf4CKNYfX0ySEC4HqAAsxrAaoJursp6F+SEiY18B8TnM5YjZhAjfm2/BkEUdGrJFMzVNaMM//J2JiFPhEAyCDys+RPqmfxIKK7ww0OLB9HoyNVab8CUuiQ/hJmmUpnJymeaEPwOf2mUtbgcYUwj6oo1W6X9oO2MmQ1OteetdSr7ec+Rj1g7jxFxxbuLDjT+JfxpsDl9y/6c9dhwQNVi7jUvRo1IA6lzTMnzJ3E6jV9TgzOCTeyJx6QOq3HWZcJPN7XR5h+wCniiak/81/yjaUHsQq9nspkSg8jFHu39DV5tHqGztaO6yF1MC13MIYi+oa8/vRpWJAlyu6kjcbuy7eEkM2syCFJLG49y2O5RnfHsgwI05TIXyPIdpsT54K0=
