language: node_js
node_js:
- '4.1'
- '0.11'
- iojs

before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN

before_script:
- jspm i
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

env:
  global:
    secure: kwJ0CwhTbjsTAD7js5XV5Jl6NadOH9JJ/3wKS7JSGf/oKARy78FKPDAoectibYaavsFpY16Gk/yAC4kgU8Zc7KyqtiIlMUSUB9iZv04uQUL2TWFHNe4Aje/xJJECiUrHSWicMAoaa8ouGwaidFLDmKb/Bcex6eR2mk6IbBwnVNnudxQ8+uHRUxOXJDaB5ZSZMkrKIvcx3gi6d1HVksOHdH5JlHWZ2zlVJvIYygwVJvhCdn3lMKMb54TzWjTYo1kZVwvqajs34Qv7+ryx+9p6Rl9sO41phf6NP6A1cC+Hn0z3m5n8eIX2o4J98T0TvsDO+KE5LM+F6yXneJwDW6KSmlhX0xGOQJ9jaK1Cry70wHWHilUGjYSC8idmIlA5Qbns221F8zEiSmgvfJa6MsHkwTMtdTT1qwBFVDLyCLABdznx5fK/bp1PZBmL7gbO/Yux5D2DbeLJiiHUV/5Cz0syPpqdlEPyRZRV16e7D9JJiOQ4Ny8KO3irI3fU6NB55KWuHyZebQGuRDuXA6r9rH9JyryJEVFki9uNF7SH0oJFVcSrCmBkNVc5vO0MW2MYgbxtUYj38GEtkd11mqOoMgEMyz1rgBvQQ79Sy46ub8x/8qHo1x0ghY1Z+5EeYa+LXqf6pOk1yHDcb+vY1Ds/LKBI6ukNmYeDSt/QW9dZKYvGJWg=
